# Generated by Django 2.2.3 on 2019-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
                ('Username', models.CharField(max_length=100)),
                ('Contact', models.CharField(blank=True, default='91+', max_length=20, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Joining_date', models.DateTimeField(auto_now=True)),
                ('CompanyName', models.CharField(blank=True, max_length=200, null=True)),
                ('Postion', models.CharField(default=0, max_length=80)),
                ('Salary', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(default='Address', max_length=200)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Pincode', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('Email', models.EmailField(max_length=150)),
                ('Password1', models.CharField(max_length=50)),
                ('Password2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
