# Generated by Django 2.2.3 on 2019-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0004_auto_20190802_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
