# Generated by Django 2.2.3 on 2019-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0006_auto_20190802_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
