# Generated by Django 2.2.3 on 2019-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0007_auto_20190802_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Postion',
        ),
        migrations.AddField(
            model_name='registration',
            name='Position',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Address',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='City',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Contact',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Pincode',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Salary',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='State',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
