# Generated by Django 2.2.3 on 2019-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0008_auto_20190805_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
